### ISSUE TITLE
[Package Issue]: AppWork.JDownloader

### ISSUE THREAD

**Issue by ave9858** [microsoft/winget-pkgs#129230]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

After installing, Windows Security sent a notification "Potentially unwanted app found" and `PUADlManager:Win32/InstallCore` is detected in `C:\Program Files\JDownloader\JDownloader2Update.exe` and `C:\Program Files\JDownloader\Uninstall JDownloader.exe`.

### Steps to reproduce

Run `winget install AppWork.JDownloader` in admin cmd with Windows Defender and Potentially unwanted app blocking enabled.

### Actual behavior

Windows Defender flags the installed files.

### Expected behavior

Installing a package shouldn't trigger security alerts.

### Environment

```raw
Windows Package Manager v1.6.3133
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19044.3693
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.3133.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

### Screenshots and Logs

![image](https://github.com/microsoft/winget-pkgs/assets/112294121/9639f357-626e-4d6a-bc93-80d4887093ff)

**Comment by stephengillie** [comment]
This package was submitted in June 2022 and updated May 2023. It's possible that this package has been added to a PUA list since having its manifest added or updated here.

**Comment by ave9858** [comment]
Not seeing the detection for `Uninstall JDownloader.exe` anymore but still getting for `JDownloader2Update.exe`

**Comment by Dragon1573** [comment]
✅ Manually verified.

![Image](https://github.com/user-attachments/assets/cffbd3e3-c316-478c-b44e-087c80e71dc5)
![Image](https://github.com/user-attachments/assets/0429e0de-385a-4875-ac9a-5eef0c5190f1)

> [!CAUTION]
> 
> After installation, I failed to uninstall it both via `winget.exe` and "Settings > Applications > Installed Apps" Panel.
> 
> Can't sure if it DOES contain harmful behavior. 😕 
> 
> ![Image](https://github.com/user-attachments/assets/536cdc34-9868-40e3-afdf-33db968b12e7)

<details><summary>Error logs</summary><p>

```text
Exception:

java.lang.NoSuchMethodError: org.appwork.updatesys.client.UpdateClient.<init>(Lorg/appwork/updatesys/client/Setup;Lorg/appwork/updatesys/client/ImplBuilder;)V
	at org.appwork.install4j.updatesys.Webinstaller$8.<init>(Webinstaller.java:686)
	at org.appwork.install4j.updatesys.Webinstaller.uninstallByID(Webinstaller.java:686)
	at org.appwork.install4j.updatesys.Webinstaller.uninstall(Webinstaller.java:625)
	at com.install4j.runtime.installer.UninstallerContextImpl$2.fetchValue(Unknown Source)
	at com.install4j.runtime.installer.helper.comm.actions.FetchObjectAction.execute(Unknown Source)
	at com.install4j.runtime.installer.helper.comm.HelperCommunication.executeActionDirect(Unknown Source)
	at com.install4j.runtime.installer.helper.comm.HelperCommunication.executeActionInt(Unknown Source)
	at com.install4j.runtime.installer.helper.comm.HelperCommunication.executeActionChecked(Unknown Source)
	at com.install4j.runtime.installer.helper.comm.HelperCommunication.fetchObjectChecked(Unknown Source)
	at com.install4j.runtime.installer.UninstallerContextImpl.performActionIntStatic(Unknown Source)
	at com.install4j.runtime.installer.UninstallerContextImpl.performActionInt(Unknown Source)
	at com.install4j.runtime.installer.ContextImpl.performAction(Unknown Source)
	at com.install4j.runtime.installer.controller.Controller.executeActions(Unknown Source)
	at com.install4j.runtime.installer.controller.Controller.handleCommand(Unknown Source)
	at com.install4j.runtime.installer.controller.Controller.start(Unknown Source)
	at com.install4j.runtime.installer.Uninstaller.runInProcess(Unknown Source)
	at com.install4j.runtime.installer.Uninstaller.main(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.exe4j.runtime.LauncherEngine.launch(Unknown Source)
	at com.exe4j.runtime.WinLauncher.main(Unknown Source)
	at com.install4j.runtime.launcher.WinLauncher.main(Unknown Source)

System properties:

java.runtime.name=Java(TM) SE Runtime Environment
exe4j.moduleName=C:\Program Files\JDownloader\Uninstall JDownloader.exe
exe4j.processCommFile=C:\Users\DRAGON~1\AppData\Local\Temp\e4j_p34856.tmp
exe4j.semaphoreName=Local\c:_program_files_jdownloader_uninstall_jdownloader.exe
sun.boot.library.path=c:\program files\jdownloader\jre\bin
java.vm.version=25.31-b07
java.vm.vendor=Oracle Corporation
java.vendor.url=http://java.oracle.com/
exe4j.consoleCodepage=cp0
path.separator=;
java.vm.name=Java HotSpot(TM) 64-Bit Server VM
file.encoding.pkg=sun.io
com.sun.jndi.rmi.object.trustURLCodebase=false
user.country=CN
user.script=
sun.os.patch.level=
install4j.exeDir=C:\Program Files\JDownloader\
java.vm.specification.name=Java Virtual Machine Specification
user.dir=C:\Program Files
java.runtime.version=1.8.0_31-b13
java.awt.graphicsenv=sun.awt.Win32GraphicsEnvironment
java.endorsed.dirs=c:\program files\jdownloader\jre\lib\endorsed
os.arch=amd64
java.io.tmpdir=C:\Users\DRAGON~1\AppData\Local\Temp\
line.separator=

java.vm.specification.vendor=Oracle Corporation
user.variant=
exe4j.tempDir=
os.name=Windows 8
com.sun.jndi.ldap.object.trustURLCodebase=false
sun.jnu.encoding=GBK
java.library.path=C:\Program Files\JDownloader\.\.install4j;C:\Program Files\PowerShell\7;C:\Program Files (x86)\oh-my-posh\bin\;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.9\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.9\libnvvp;C:\Applications\Python\Scripts\;C:\Applications\Python\;C:\Applications\Apache\Maven\bin;C:\Program Files\Eclipse Adoptium\jdk-23.0.2.7-hotspot\bin;D:\Repository\vcpkg;C:\Program Files\NVIDIA\CUDNN\v9.5\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\dotnet\;C:\Program Files\WinGet\Links;C:\Program Files\ncat\;C:\Program Files\BandiSoft\BandiZip\Bandizip;C:\Program Files\BandiSoft\Bandizip;C:\Program Files\7-Zip;C:\Program Files (x86)\Inno Setup 6;C:\Applications\Microsoft\VSCode\bin;C:\Program Files\NVIDIA Corporation\NVIDIA app\NvDLISR;C:\Program Files\Komac\bin;C:\Program Files\Bandizip\;C:\Program Files\gsudo\Current;C:\Program Files\MarkText;C:\Applications\Git\Git\cmd;C:\Program Files\PowerShell\7\;C:\Program Files\Neovim\bin;C:\Program Files\GitHub CLI\;C:\Program Files\NVIDIA Corporation\Nsight Compute 2025.2.0\;C:\Program Files\CMake\bin;C:\Program Files\Docker\Docker\resources\bin;C:\Program Files\nodejs\;D:\PackageCache\cargo\bin;c:\users\dragon1573\appdata\local\pnpm;c:\users\dragon1573\appdata\local\microsoft\windowsapps;c:\users\dragon1573\appdata\local\programs\oh-my-posh\bin;c:\users\dragon1573\.dotnet\tools;c:\users\dragon1573\appdata\roaming\code\user\globalstorage\ms-vscode-remote.remote-containers\cli-bin;C:\Users\Dragon1573\AppData\Local\Programs\oh-my-posh\bin;C:\Users\Dragon1573\AppData\Local\Microsoft\WindowsApps;C:\Users\Dragon1573\.dotnet\tools;C:\Users\Dragon1573\AppData\Local\gitkraken\bin;C:\Users\Dragon1573\AppData\Local\Microsoft\WinGet\Links;C:\Users\Dragon1573\AppData\Roaming\npm;c:\Users\Dragon1573\AppData\Roaming\Code\User\globalStorage\github.copilot-chat\debugCommand;c:\program files\jdownloader\jre\bin
sun.awt.enableExtraMouseButtons=true
java.specification.name=Java Platform API Specification
java.class.version=52.0
sun.management.compiler=HotSpot 64-Bit Tiered Compilers
exe4j.isInstall4j=true
os.version=6.2
java.rmi.server.useCodebaseOnly=true
user.home=C:\Users\Dragon1573
user.timezone=Asia/Shanghai
java.awt.printerjob=sun.awt.windows.WPrinterJob
file.encoding=GBK
java.specification.version=1.8
java.class.path=C:\Program Files\JDownloader\.install4j\i4jruntime.jar;C:\Program Files\JDownloader\.\.install4j\user.jar;C:\Program Files\JDownloader\.\.install4j\user\proxyVole.jar;;C:\Program Files\JDownloader\jre\lib\deploy.jar;C:\Program Files\JDownloader\jre\lib\plugin.jar;C:\Program Files\JDownloader\JDownloader.jar
user.name=Dragon1573
java.vm.specification.version=1.8
sun.java.command=C:\Program Files\JDownloader\Uninstall JDownloader.exe
java.home=c:\program files\jdownloader\jre
sun.arch.data.model=64
exe4j.launchName=C:\Program Files\JDownloader\Uninstall JDownloader.exe
user.language=zh
java.specification.vendor=Oracle Corporation
awt.toolkit=sun.awt.windows.WToolkit
java.vm.info=mixed mode
exe4j.unextractedPosition=0
java.version=1.8.0_31
java.ext.dirs=c:\program files\jdownloader\jre\lib\ext;C:\WINDOWS\Sun\Java\lib\ext
sun.boot.class.path=c:\program files\jdownloader\jre\lib\resources.jar;c:\program files\jdownloader\jre\lib\rt.jar;c:\program files\jdownloader\jre\lib\sunrsasign.jar;c:\program files\jdownloader\jre\lib\jsse.jar;c:\program files\jdownloader\jre\lib\jce.jar;c:\program files\jdownloader\jre\lib\charsets.jar;c:\program files\jdownloader\jre\lib\jfr.jar;c:\program files\jdownloader\jre\classes
install4j.appDir=C:\Program Files\JDownloader\
java.vendor=Oracle Corporation
file.separator=\
com.sun.jndi.cosnaming.object.trustURLCodebase=false
java.vendor.url.bug=http://bugreport.sun.com/bugreport/
sun.io.unicode.encoding=UnicodeLittle
sun.cpu.endian=little
install4j.systemLanguage=zh
sun.desktop=windows
sun.cpu.isalist=amd64
```

</p></details>

**Comment by isnikulin** [comment]
Since about last month installing AppWork.JDownloader via winget is broken:

<img width="658" height="119" alt="Image" src="https://github.com/user-attachments/assets/21313192-6bbe-4c36-a9b7-22efc0a571f0" />

Following the installer url https://installer.jdownloader.org/JD2SilentSetup_x64.exe downloads a 87 byte file, which seems to be an error on the creator's side.

**Comment by SalahAdDin** [comment]
It is not up anymore.
